// restaurants
export const RESTAURANTS_FETCHING_ACTION = "RESTAURANTS/FETCHING"
export const RESTAURANTS_FETCH_SUCCESS_ACTION = "RESTAURANTS/SUCCESS"

// foods
export const FOODS_FETCHING_ACTION = "FOODS/FETCHING"
export const FOODS_FETCH_SUCCESS_ACTION = "FOODS/SUCCESS"
